### ISSUE TITLE
facing error while running the Yahoo Music notebook

### ISSUE THREAD

**Issue by Muskaan06** [OweysMomenzada/Graph-Neural-Networks-for-effecient-Recommender-Systems#1]
Hi,
I am trying to understand GNN and I came across your project a few days ago. I tried to run the Yahoo Music colab notebook but I am facing a problem with the **DGL** package installation due to which I am getting out of bound error. The colab does not support python version > 3.7. I have tried implementing this using jupyter notebook on my laptop but the error remains the same. Can you suggest any other alternative for this?

**Comment by OweysMomenzada** [comment]
Hey,

thank you for reaching out.
Please paste the full error history, that would help me more to traceback the origin of the error.

Could you run the other Notebooks without any further issues? 
Did you consider the requirements (especially installing DGL==0.5.3: newer or older versions can cause memory errors)?

I ran the notebooks with Python 3.8. but did not try any other versions. It would surprise me, if errors occurred by using Python 3.7.

 keep me posted

**Comment by OweysMomenzada** [comment]
No answer. Issue closed
