### ISSUE TITLE
RMSE vs MSE

### ISSUE THREAD

**Issue by bofgenerations** [OweysMomenzada/Graph-Neural-Networks-for-effecient-Recommender-Systems#2]
Hello,
I saw that in the code, the error is calculated as mean_squared_error(predictions, ratings, squared=True), is that the MSE or RMSE? Thank you

**Comment by OweysMomenzada** [comment]
Hey,

here, we use squared=True, which calculates the error in RMSE. 
If you need MSE, turn squared to false.
