### ISSUE TITLE
remove items from testset

### ISSUE THREAD

**Issue by bofgenerations** [OweysMomenzada/Graph-Neural-Networks-for-effecient-Recommender-Systems#3]
Hello,
First I would like to thank you for making this graph model available in the format of python notebook. Because I needed to modify the dataset, I noticed an issue in the part of dropping the items/movies that are not in the trainset from the testset. It seems that the index of the testset dataframe does not reset after dropping the row, but when looking for the item to drop from the testset, the code uses the index of item in the list and that index might have already been removed already. 

```
# Datensatzvorbereitung

# entferne Items von testset die nicht im trainset sind. 
ueberschussTests = list(set(testset['itemId']).difference(set(trainset['itemId']))) #speichere differenz der Menge
i = 0
while i< len(ueberschussTests):  
    index = list(testset['itemId']).index(ueberschussTests[i]) #speichere Index vom Ueberschuss
    testset = testset.drop([index]) #lösche Items die überschüssig sind. 
    i = i+1
```
Inside of the while loop, what I did is to replace the two lines by  
`testset.drop(testset[testset['itemId']==ueberschussTests[i]].index.tolist(), inplace=True)`

**Comment by OweysMomenzada** [comment]
Thank you for your contribution, I will check your suggestion and will apply it to the notebooks if needed.
